### ISSUE TITLE
Mono V2 widget doesn't send the expected code in the onSuccess Hook

### ISSUE THREAD

**Issue by k1ycee** [wiseminds/mono-flutter#17]
So we have this widget all setup and we expect to receive a code at the onSuccess hook, but this code doesn't come in but after much debugging we can see that the code is being sent from the onClose hook, but the onClose hook is not designed to do this.
Please not that this only happens when we switch to the v2 widget, if we switch back to the v1 widget we don't experience this issue.

**Comment by k1ycee** [comment]
I can close this issue gracefully now.

**Comment by wiseminds** [comment]
@k1ycee is the issue resolved now ?
