### ISSUE TITLE
Fintechs not showing up

### ISSUE THREAD

**Issue by kehindeegunjobi93** [wiseminds/mono-flutter#2]
Mono recently added investment platforms like chaka, trove, bamboo. When I search on mono-flutter, they are not showing up

**Comment by wiseminds** [comment]
I will check this issue and get back to you

**Comment by kehindeegunjobi93** [comment]
> I will check this issue and get back to you

I have reached Mono on their slack. They said they are working on it. I guess you can close this issue now. Thank you
