### ISSUE TITLE
Null safety error on latest version (1.1.3)

### ISSUE THREAD

**Issue by timoladoyinbo** [wiseminds/mono-flutter#6]
Hi, thanks for the time put into developing this package.

I've discovered a null safety issue while building the latest version (1.1.3). The error is from the WidgetBinding instance in the `mono_web_view.dart` file.

The actual error is this ` Error: Property 'focusManager' cannot be accessed on 'WidgetsBinding?' because it is potentially null.`

Flutter version: 2.10.3

I'll do a pull request that fixes this.

**Comment by kusayp** [comment]
Hi, Please am also facing the same issue. If any of the admins could please merge the code after review.
Thank you.

**Comment by wiseminds** [comment]
I will check it out and let you know.
